### PR TITLE
fix generated incorrectly formatted json

### PR DESCRIPTION
**Pull request by cloverzrg**

### CODE REVIEW

**Review by baywet — COMMENTED** [review]
Hi @cloverzrg ,
Thanks for the contribution.
Could you add some unit tests please and provide additional context on what was the original issue?

**Comment by baywet** [comment]
Gentle reminder @cloverzrg

**Comment by cloverzrg** [comment]
> Gentle reminder @cloverzrg

Sorry for delay reply , i am wondering that why there are no "{}" on the return value of  `GetSerializedContent()`

**Comment by baywet** [comment]
Can you share the code you used to serialize the object?

**Comment by cloverzrg** [comment]
> Can you share the code you used to serialize the object?

just return json to front end， my personal project

**Comment by baywet** [comment]
to be more specific did you writer `myObject.Serialize(mySerializationWriter)` or `mySerializationWriter.WriteObjectValue(nil, myObject)` ?

**Comment by cloverzrg** [comment]
I have copy the microsoft/kiota-serialization-json-go to  the util package.

```
package util

import (
	"github.com/microsoft/kiota-abstractions-go/serialization"
)

func ToJson(data serialization.Parsable) (res string, err error) {
	if data == nil {
		return "{}", nil
	}
	writer := NewJsonSerializationWriter()
	err = data.Serialize(writer)
	if err != nil {
		return res, err
	}
	content, err := writer.GetSerializedContent()
	if err != nil {
		return res, err
	}
	return string(content), nil
}
```

**Comment by cloverzrg** [comment]
Am I using the pkg in the wrong way?

**Comment by baywet** [comment]
Yes you need to replace `err = data.Serialize(writer)` by `err = writer.writeObjectValue(nil, data)`

**Comment by cloverzrg** [comment]
thx

**Pull request closed without merging**
